commands:
  default: >-
    []
  json_schema: >-
    {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "trigger": {
            "type": "string",
            "description": "Slash command to watch for (e.g. \"/template\")."
          },
          "templates": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "label": {
                  "type": "string",
                  "description": "Dropdown label"
                },
                "text": {
                  "type": "string",
                  "description": "Snippet text (use \\n or actual newlines)"
                }
              },
              "required": ["label", "text"]
            },
            "description": "List of {label, text} objects for this command"
          }
        },
        "required": ["trigger", "templates"]
      }
    }
  client: true
  description: |
    Define an array of commands. Each command must have:
    - trigger: the slash‐command (e.g. "/template")
    - templates: an array of {label, text} pairs to display when that trigger is typed.
template_dropdown_allowed_groups:
  type: list
  list_type: group
  default: ""
  client: true
  description: "Only users in these groups can trigger the /​… template dropdown."
